[files.assets.config]
target_dir="src/zimscraperlib/rewriting/statics"
execute_after=[
    "cd ../../../../ && python rules/generate_rules.py", # generate Python (and JS) rules
]

[files.assets.actions."wombat.js"]
action="get_file"
source="https://cdn.jsdelivr.net/npm/@webrecorder/wombat@3.8.2/dist/wombat.js"
target_file="wombat.js"

# wombatSetup.js is supposed to be built locally from files in javascript folder.
# Should someone not have proper skills / tooling / knowledge, or simply install from
# sdist / Github repo directly, without any advanced knowledge of this specificity, the
# configuration below ensures that wombatSetup.js is downloaded from dev.kiwix.org,
# where we have the latest version from `main` branch. wheel contains the wombatSetup.js
# which was built at the same time than the wheel. (reminder: get_file action does not
# overwrite a file which already exists)
[files.assets.actions."wombatSetup.js"]
action="get_file"
source="https://dev.kiwix.org/zimscraperlib/wombatSetup.js"
target_file="wombatSetup.js"
